export const movies = [
    {
      id: 1,
      title: "John Wick",
      type: "movie",
      released: "24 Mar 2023",
      duration: "169 min",
      genre: "Action, Crime, Thriller",
      director: "Chad Stahelski",
      cast: "Keanu Reeves, Laurence Fishburne, George Georgiou",
      poster: "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 2,
      title: "Barbie",
      type: "movie",
      released: "21 Jul 2023",
      duration: "114 min",
      genre: "Adventure, Comedy, Fantasy",
      director: "Greta Gerwig",
      cast: "Margot Robbie, Ryan Gosling, Issa Rae",
      poster: "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
     
    },
    {
      id: 3,
      title: "GOG Vol. 3",
      type: "movie",
      released: "05 May 2023",
      duration: "150 min",
      genre: "Action, Adventure, Comedy",
      director: "James Gunn",
      cast: "Chris Pratt, Chukwudi Iwuji, Bradley Cooper",
      poster: "https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 4,
      title: "The Little Mermaid",
      type: "movie",
      released: "26 May 2023",
      duration: "135 min",
      genre: "Adventure, Family, Fantasy",
      director: "Rob Marshall",
      cast: "Halle Bailey, Jonah Hauer-King, Melissa McCarthy",
      poster: "https://m.media-amazon.com/images/M/MV5BYTUxYjczMWUtYzlkZC00NTcwLWE3ODQtN2I2YTIxOTU0ZTljXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 5,
      title: "Oppenheimer",
      type: "movie",
      released: "21 Jul 2023",
      duration: "180 min",
      genre: "Biography, Drama, History",
      director: "Christopher Nolan",
      cast: "Cillian Murphy, Emily Blunt, Matt Damon",
      poster: "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 6,
      title: "Spider-Man",
      type: "movie",
      released: "02 Jun 2023",
      duration: "140 min",
      genre: "Animation, Action, Adventure",
      director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
      cast: "Shameik Moore, Hailee Steinfeld, Brian Tyree Henry",
      poster: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 7,
      title: "The Super Mario",
      type: "concert",
      released: "05 Apr 2023",
      duration: "92 min",
      genre: "Animation, Adventure, Comedy",
      director: "Aaron Horvath, Michael Jelenic, Pierre Leduc",
      cast: "Chris Pratt, Anya Taylor-Joy, Charlie Day",
      poster: "https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    },
    {
      id: 8,
      title: "Killers of Flower Moon",
      type: "concert",
      released: "20 Oct 2023",
      duration: "206 min",
      genre: "Crime, Drama, History",
      director: "Martin Scorsese",
      cast: "Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
      poster: "https://m.media-amazon.com/images/M/MV5BMjE4ZTZlNDAtM2Q3YS00YjFhLThjN2UtODg2ZGNlN2E2MWU2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_SX300.jpg",
      ticketPriceNormal: "500",
      ticketPriceVip: "1500"
    }
  ];